import * as path from 'path';

import type { HookFile, HookFinding, HookRuleId, HookRulePolicy } from './types';

// quality-gate: allow handler-before-send: this file intentionally defines handler/send detector patterns.

export const DEFAULT_HOOK_RULE_POLICY: HookRulePolicy = {
  'conflict-marker': 'block',
  'secret-literal': 'block',
  'package-manager': 'block',
  'typescript-any': 'block',
  'weak-test': 'block',
  'low-value-static-ui-test': 'block',
  'handler-before-send': 'block',
  'pre-cr-required': 'block',
  'pre-cr-unavailable': 'block',
  'pre-cr-failed': 'block',
  'oversized-source': 'warn'
};

const CODE_EXTENSIONS = new Set(['.js', '.jsx', '.mjs', '.cjs', '.ts', '.tsx']);
const SOURCE_EXTENSIONS = new Set(['.js', '.jsx', '.mjs', '.cjs', '.ts', '.tsx', '.py', '.sh']);
const TEXT_EXTENSIONS = new Set([
  '.css',
  '.env',
  '.html',
  '.js',
  '.jsx',
  '.json',
  '.md',
  '.mjs',
  '.py',
  '.sh',
  '.sql',
  '.toml',
  '.ts',
  '.tsx',
  '.txt',
  '.yaml',
  '.yml',
  '.zsh'
]);
const TEST_PATH_PARTS = new Set(['test', 'tests', '__tests__', 'spec', 'specs']);
const GENERATED_PATH_PARTS = new Set(['generated']);
const GENERATED_FILE_MARKERS = [
  '@generated',
  'auto-generated',
  'autogenerated',
  'generated by',
  'do not edit',
  'artifact rows are json-synced'
];
const MESSAGE_EVENT = 'message';
const HANDLER_PATTERNS = [
  `addEventListener("${MESSAGE_EVENT}"`,
  `addEventListener('${MESSAGE_EVENT}'`,
  `.on("${MESSAGE_EVENT}"`,
  `.on('${MESSAGE_EVENT}'`,
  `.once("${MESSAGE_EVENT}"`,
  `.once('${MESSAGE_EVENT}'`,
  ['.on', MESSAGE_EVENT].join('')
];
const SEND_PATTERNS = ['.postMessage(', 'postMessage('];
const ALLOW_HANDLER_MARKER = 'quality-gate: allow handler-before-send';
const ALLOW_SECRET_MARKER = 'quality-gate: allow secret';
const ALLOW_STATIC_UI_TEST_MARKER = 'quality-gate: allow static-ui-test';
const SECRET_RE =
  /\b(api[_-]?key|secret|token|password|private[_-]?key|client[_-]?secret)\b\s*[:=]\s*['"][^'"\s]{12,}['"]/i;
const TS_ANY_RE = /(:\s*any\b|\bas\s+any\b|<\s*any\s*>|Array\s*<\s*any\s*>)/;
const PACKAGE_MANAGER_RE = /\b(npm|yarn)\s+(install|add|run|test|ci|start|build|lint|exec)\b/;
const CONFLICT_MARKERS = ['<<<<<<< ', '=======', '>>>>>>> '];
const STATIC_UI_RENDER_PATTERNS = ['renderToStaticMarkup(', '@testing-library/react'];
const STATIC_UI_COPY_PATTERNS = ['.toContain(', '.not.toContain(', 'getByText(', 'queryByText('];
const UI_BEHAVIOR_PATTERNS = [
  'fireEvent.',
  'userEvent.',
  'waitFor(',
  'act(',
  '.toHaveBeenCalled',
  '.dispatchEvent(',
  '.click('
];

export function evaluateHookRules(files: HookFile[], policy: HookRulePolicy): HookFinding[] {
  const findings: HookFinding[] = [];

  for (const file of files) {
    if (!shouldScanText(file.path)) {
      continue;
    }

    findings.push(
      ...findConflictMarkers(file, policy),
      ...findSecretLiterals(file, policy),
      ...findPackageManagerViolations(file, policy),
      ...findTypescriptAny(file, policy),
      ...findOversizedSource(file, policy),
      ...findWeakPythonTest(file, policy),
      ...findLowValueStaticUiTest(file, policy),
      ...findHandlerBeforeSend(file, policy)
    );
  }

  return findings;
}

export function hasSourceFiles(paths: string[]): boolean {
  return paths.some((filePath) => SOURCE_EXTENSIONS.has(path.extname(filePath).toLowerCase()));
}

function shouldScanText(filePath: string): boolean {
  const suffix = path.extname(filePath).toLowerCase();
  return TEXT_EXTENSIONS.has(suffix) || ['.env', '.env.local', '.env.production', 'Dockerfile'].includes(path.basename(filePath));
}

function findConflictMarkers(file: HookFile, policy: HookRulePolicy): HookFinding[] {
  const findings: HookFinding[] = [];
  file.text.split(/\r?\n/).forEach((line, index) => {
    if (CONFLICT_MARKERS.some((marker) => line.startsWith(marker))) {
      pushFinding(findings, policy, file.path, index + 1, 'conflict-marker', 'remove merge conflict marker');
    }
  });
  return findings;
}

function findSecretLiterals(file: HookFile, policy: HookRulePolicy): HookFinding[] {
  const findings: HookFinding[] = [];
  file.text.split(/\r?\n/).forEach((line, index) => {
    if (line.includes(ALLOW_SECRET_MARKER)) {
      return;
    }
    const lowered = line.toLowerCase();
    if (['example', 'placeholder', 'redacted', 'dummy'].some((marker) => lowered.includes(marker))) {
      return;
    }
    if (SECRET_RE.test(line)) {
      pushFinding(
        findings,
        policy,
        file.path,
        index + 1,
        'secret-literal',
        `possible secret literal; move to env or add \`${ALLOW_SECRET_MARKER}: <reason>\``
      );
    }
  });
  return findings;
}

function findPackageManagerViolations(file: HookFile, policy: HookRulePolicy): HookFinding[] {
  const findings: HookFinding[] = [];
  if (['package-lock.json', 'yarn.lock'].includes(path.basename(file.path))) {
    pushFinding(findings, policy, file.path, 1, 'package-manager', 'use pnpm; do not commit npm/yarn lockfiles');
    return findings;
  }

  file.text.split(/\r?\n/).forEach((line, index) => {
    if (PACKAGE_MANAGER_RE.test(line)) {
      pushFinding(findings, policy, file.path, index + 1, 'package-manager', 'use pnpm instead of npm/yarn commands');
    }
  });
  return findings;
}

function findTypescriptAny(file: HookFile, policy: HookRulePolicy): HookFinding[] {
  if (!['.ts', '.tsx'].includes(path.extname(file.path).toLowerCase()) || isTestPath(file.path)) {
    return [];
  }

  const findings: HookFinding[] = [];
  file.text.split(/\r?\n/).forEach((line, index) => {
    const stripped = line.trim();
    if (stripped.startsWith('//') || line.includes('quality-gate: allow any')) {
      return;
    }
    if (TS_ANY_RE.test(line)) {
      pushFinding(findings, policy, file.path, index + 1, 'typescript-any', 'avoid `any` in production TypeScript; use a concrete type or document a narrow exception');
    }
  });
  return findings;
}

function findOversizedSource(file: HookFile, policy: HookRulePolicy): HookFinding[] {
  const suffix = path.extname(file.path).toLowerCase();
  if (!SOURCE_EXTENSIONS.has(suffix) || isGeneratedPath(file.path) || hasGeneratedMarker(file.text)) {
    return [];
  }

  const nonblankLines = file.text.split(/\r?\n/).filter((line) => line.trim().length > 0).length;
  const limit = oversizedLimit(suffix);
  if (nonblankLines <= limit) {
    return [];
  }

  const findings: HookFinding[] = [];
  pushFinding(
    findings,
    policy,
    file.path,
    1,
    'oversized-source',
    `${nonblankLines} nonblank lines exceeds production source size limit ${limit}; split by responsibility or document an exception`
  );
  return findings;
}

function findWeakPythonTest(file: HookFile, policy: HookRulePolicy): HookFinding[] {
  if (path.extname(file.path).toLowerCase() !== '.py' || !isTestPath(file.path)) {
    return [];
  }
  if (/\bassert\b|pytest\.raises|self\.assert|unittest\./.test(file.text)) {
    return [];
  }

  const findings: HookFinding[] = [];
  pushFinding(findings, policy, file.path, 1, 'weak-test', 'test file has no clear assertion; add behavior assertions or document why this is smoke-only');
  return findings;
}

function findLowValueStaticUiTest(file: HookFile, policy: HookRulePolicy): HookFinding[] {
  if (!['.ts', '.tsx', '.js', '.jsx'].includes(path.extname(file.path).toLowerCase()) || !isTestPath(file.path)) {
    return [];
  }
  if (file.text.includes(ALLOW_STATIC_UI_TEST_MARKER)) {
    return [];
  }
  if (!STATIC_UI_RENDER_PATTERNS.some((pattern) => file.text.includes(pattern))) {
    return [];
  }
  if (!STATIC_UI_COPY_PATTERNS.some((pattern) => file.text.includes(pattern))) {
    return [];
  }
  if (UI_BEHAVIOR_PATTERNS.some((pattern) => file.text.includes(pattern))) {
    return [];
  }

  const findings: HookFinding[] = [];
  pushFinding(
    findings,
    policy,
    file.path,
    1,
    'low-value-static-ui-test',
    `static UI copy test has low regression value; add behavior coverage or \`${ALLOW_STATIC_UI_TEST_MARKER}: <reason>\``
  );
  return findings;
}

function findHandlerBeforeSend(file: HookFile, policy: HookRulePolicy): HookFinding[] {
  if (!CODE_EXTENSIONS.has(path.extname(file.path).toLowerCase())) {
    return [];
  }

  const lines = file.text.split(/\r?\n/);
  const findings: HookFinding[] = [];
  lines.forEach((line, index) => {
    if (!HANDLER_PATTERNS.some((pattern) => line.includes(pattern))) {
      return;
    }
    if (hasAllowMarker(lines, index, ALLOW_HANDLER_MARKER)) {
      return;
    }
    const window = lines.slice(index, index + 41);
    if (window.some((candidate) => SEND_PATTERNS.some((pattern) => candidate.includes(pattern)))) {
      pushFinding(
        findings,
        policy,
        file.path,
        index + 1,
        'handler-before-send',
        `message handler appears before postMessage; send first or document a real runtime reason with \`${ALLOW_HANDLER_MARKER}: <reason>\``
      );
    }
  });
  return findings;
}

export function findingForRule(
  policy: HookRulePolicy,
  pathName: string,
  line: number,
  rule: HookRuleId,
  message: string
): HookFinding | null {
  const severity = policy[rule] ?? DEFAULT_HOOK_RULE_POLICY[rule] ?? 'block';
  if (severity === 'off') {
    return null;
  }
  return {
    path: pathName,
    line,
    rule,
    message,
    severity
  };
}

function pushFinding(
  findings: HookFinding[],
  policy: HookRulePolicy,
  pathName: string,
  line: number,
  rule: HookRuleId,
  message: string
): void {
  const finding = findingForRule(policy, pathName, line, rule, message);
  if (finding) {
    findings.push(finding);
  }
}

function isTestPath(filePath: string): boolean {
  return filePath.split(/[\\/]/).some((part) => TEST_PATH_PARTS.has(part.toLowerCase())) || /\.(test|spec)\.[cm]?[jt]sx?$/.test(filePath);
}

function isGeneratedPath(filePath: string): boolean {
  return filePath.split(/[\\/]/).some((part) => GENERATED_PATH_PARTS.has(part.toLowerCase()));
}

function hasGeneratedMarker(text: string): boolean {
  const prefix = text.slice(0, 2048).toLowerCase();
  return GENERATED_FILE_MARKERS.some((marker) => prefix.includes(marker));
}

function hasAllowMarker(lines: string[], index: number, marker: string): boolean {
  return lines[index]?.includes(marker) || lines[index - 1]?.includes(marker);
}

function oversizedLimit(suffix: string): number {
  if (suffix === '.py') {
    return 700;
  }
  if (CODE_EXTENSIONS.has(suffix)) {
    return 500;
  }
  return 500;
}
