#!/usr/bin/env bash
#
# A wizard - walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# --------------------------------------------------------------------------
# Wizard library - delightful, consistent UX. Identical across every wizard.
# --------------------------------------------------------------------------

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear - wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" - opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages * about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later - it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> - clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s> Stage %s/%s * %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." - a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." - a numbered-feeling action the human takes in the browser.
step() { printf '  %s*%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s! %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL - open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %sopening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser - visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser - visit it manually: $url"
}

# pause "msg" - wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" - y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY - current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" - read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" - like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE - upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %sOK wrote%s %s -> %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE - set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %sOK set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name - gh not ready; set it later"
}

# set_var NAME VALUE - set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %sOK set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name - gh not ready; set it later"
}

# finish - clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  OK Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# --------------------------------------------------------------------------
# STAGES - author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# --------------------------------------------------------------------------

TOTAL_STAGES=7
TOTAL_MINUTES=25

run_cmd() {
  say "$ $*"
  "$@"
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    warn "missing required command: $1"
    exit 1
  fi
}

inspect_package_tarball() {
  local package_dir="$1" package_name="$2" tmp_dir tarball
  tmp_dir="$(mktemp -d)"
  say "$ corepack pnpm --dir $package_dir pack --pack-destination $tmp_dir"
  corepack pnpm --dir "$package_dir" pack --pack-destination "$tmp_dir"
  tarball="$(find "$tmp_dir" -maxdepth 1 -name '*.tgz' -type f | head -n 1)"
  if [[ -z "$tarball" ]]; then
    warn "could not find packed tarball for $package_name"
    rm -rf "$tmp_dir"
    exit 1
  fi
  say "Inspecting $package_name tarball contents:"
  tar -tzf "$tarball" | sed 's#^package/##'
  if ! tar -tzf "$tarball" | grep -q '^package/LICENSE$'; then
    warn "$package_name tarball is missing LICENSE"
    rm -rf "$tmp_dir"
    exit 1
  fi
  rm -rf "$tmp_dir"
}

require_exact_publish_confirmation() {
  local key="$1" expected="$2" prompt="$3"
  ask "$key" "$prompt"
  if [[ "${!key}" != "$expected" ]]; then
    warn "confirmation did not match '$expected'; stopping before publish."
    exit 1
  fi
}

package_version_or_empty() {
  npm view "$1" version 2>/dev/null || true
}

npm_org_visible() {
  npm org ls pre-cr >/dev/null 2>&1
}

banner "Pre-CR npm publish"

stage "Preflight" 3
say "This wizard publishes only the npm runtime packages:"
step "@pre-cr/core"
step "@pre-cr/server"
say "It intentionally does not npm-publish pre-cr-suite; keep that as VS Code Marketplace/VSIX."
say "It also ignores the untracked .quality-runner/ directory by using pnpm publish --no-git-checks."
require_cmd npm
require_cmd pnpm
require_cmd node
require_cmd git
require_cmd corepack
require_cmd tar
run_cmd npm whoami
run_cmd node -e "const pkgs=['packages/core/package.json','packages/server/package.json','packages/vscode-client/package.json']; for (const f of pkgs) { const p=require('./'+f); console.log(f, p.name, p.version); }"
run_cmd git status --short
confirm "Continue only if npm whoami is jakyeamos33 and the package names above look right?" || exit 1

stage "Create or verify npm org" 5
if npm_org_visible; then
  say "Already done: npm org/scope pre-cr is visible to this npm login."
else
  say "The npm CLI can manage an existing org, but cannot create a missing org."
  open_url "https://www.npmjs.com/org/create"
  step "In npm, create an organization named: pre-cr"
  step "Make jakyeamos33 an owner or admin for that org."
  step "Close the npm org creation tab after the org is created."
  pause "Press Enter after the pre-cr npm org exists."
  if npm_org_visible; then
    say "Verified npm org/scope pre-cr is visible to this npm login."
  else
    warn "npm still cannot see the pre-cr org/scope. Create it in the browser, then rerun this wizard."
    exit 1
  fi
fi

stage "Final local gates" 8
say "Already done in this release-prep flow: lint, typecheck, build, test, headless smoke, VSIX package, and commit hook passed."
say "Rerunning is safest if package source changed after those checks."
if confirm "Rerun lint, typecheck, build, test, headless smoke, and VSIX package now?"; then
  run_cmd pnpm lint
  run_cmd pnpm typecheck
  run_cmd pnpm build
  run_cmd pnpm test
  run_cmd pnpm test:headless-beta
  run_cmd pnpm package
else
  say "Continuing with the completed release-prep verification already recorded for this flow."
fi

stage "NPM pack inspection" 3
say "Already done in this release-prep flow: both publishable package tarballs were inspected successfully."
say "Project-pinned pnpm 9 does not support pack --dry-run, so this wizard packs to a temp directory, prints contents, verifies LICENSE, then deletes the temp tarball."
if confirm "Rerun the two npm package pack inspections now?"; then
  inspect_package_tarball "packages/core" "@pre-cr/core"
  inspect_package_tarball "packages/server" "@pre-cr/server"
  say "Inspect the tarball contents above. They should include dist files, LICENSE, README, and package.json."
  confirm "Do the package contents look right?" || exit 1
else
  say "Continuing with the completed package inspections already recorded for this flow."
fi

stage "Publish @pre-cr/core" 2
CORE_VERSION="$(package_version_or_empty @pre-cr/core)"
if [[ "$CORE_VERSION" == "0.1.0" ]]; then
  say "@pre-cr/core@0.1.0 is already visible on npm; skipping publish."
else
  say "This is irreversible for version 0.1.0 once npm accepts it."
  say "If your account uses 2FA, npm/pnpm may prompt for an OTP."
  require_exact_publish_confirmation PUBLISH_CORE_CONFIRM "publish @pre-cr/core@0.1.0" "Type exactly 'publish @pre-cr/core@0.1.0' to publish core:"
  run_cmd corepack pnpm publish --filter @pre-cr/core --access public --no-git-checks
fi

stage "Publish @pre-cr/server" 2
CORE_VERSION="$(package_version_or_empty @pre-cr/core)"
if [[ "$CORE_VERSION" != "0.1.0" ]]; then
  warn "@pre-cr/core@0.1.0 is not visible on npm yet. Publish core first, then rerun this wizard."
  exit 1
fi
SERVER_VERSION="$(package_version_or_empty @pre-cr/server)"
if [[ "$SERVER_VERSION" == "0.1.0" ]]; then
  say "@pre-cr/server@0.1.0 is already visible on npm; skipping publish."
else
  say "This is irreversible for version 0.1.0 once npm accepts it."
  say "If your account uses 2FA, npm/pnpm may prompt for an OTP."
  require_exact_publish_confirmation PUBLISH_SERVER_CONFIRM "publish @pre-cr/server@0.1.0" "Type exactly 'publish @pre-cr/server@0.1.0' to publish server:"
  run_cmd corepack pnpm publish --filter @pre-cr/server --access public --no-git-checks
fi

stage "Post-publish verification" 2
run_cmd npm view @pre-cr/core version
run_cmd npm view @pre-cr/server version
say "Skipped npm publish for pre-cr-suite by design."
say "Next separate action, if desired: package/publish the VS Code extension through VS Code Marketplace tooling."

finish
