#!/usr/bin/env bash
#
# A wizard - walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# --------------------------------------------------------------------------
# Wizard library - delightful, consistent UX. Identical across every wizard.
# --------------------------------------------------------------------------

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear - wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" - opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages * about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later - it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> - clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s> Stage %s/%s * %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." - a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." - a numbered-feeling action the human takes in the browser.
step() { printf '  %s*%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s! %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL - open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %sopening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser - visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser - visit it manually: $url"
}

# pause "msg" - wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" - y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY - current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" - read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" - like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE - upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %sOK wrote%s %s -> %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE - set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %sOK set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name - gh not ready; set it later"
}

# set_var NAME VALUE - set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %sOK set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name - gh not ready; set it later"
}

# finish - clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  OK Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# --------------------------------------------------------------------------
# STAGES - author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# --------------------------------------------------------------------------

TOTAL_STAGES=7
TOTAL_MINUTES=22

PUBLISHER_ID="jakye"
EXTENSION_NAME="pre-cr-suite"
EXTENSION_VERSION="0.1.0"
EXTENSION_ID="${PUBLISHER_ID}.${EXTENSION_NAME}"
EXTENSION_DIR="packages/vscode-client"
VSIX_FILE="${EXTENSION_NAME}-${EXTENSION_VERSION}.vsix"
VSIX_PATH="${EXTENSION_DIR}/${VSIX_FILE}"

run_cmd() {
  say "$ $*"
  "$@"
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    warn "missing required command: $1"
    exit 1
  fi
}

marketplace_version_or_empty() {
  corepack pnpm --filter "$EXTENSION_NAME" exec vsce show "$EXTENSION_ID" --json 2>/dev/null \
    | node -e "let s=''; process.stdin.on('data', d => s += d); process.stdin.on('end', () => { try { const data=JSON.parse(s); console.log(data?.versions?.[0]?.version || data?.version || ''); } catch { process.exit(0); } });" || true
}

verify_vsix_contents() {
  if [[ ! -f "$VSIX_PATH" ]]; then
    warn "missing VSIX: $VSIX_PATH"
    exit 1
  fi
  say "Inspecting $VSIX_PATH:"
  unzip -l "$VSIX_PATH"
  if unzip -l "$VSIX_PATH" | grep -E '\.map($|[[:space:]])' >/dev/null 2>&1; then
    warn "VSIX contains source maps; rebuild/package before publishing."
    exit 1
  fi
  if ! unzip -l "$VSIX_PATH" | grep -q 'extension/dist/extension.js'; then
    warn "VSIX is missing extension/dist/extension.js"
    exit 1
  fi
  if ! unzip -l "$VSIX_PATH" | grep -q 'extension/dist/server.js'; then
    warn "VSIX is missing extension/dist/server.js"
    exit 1
  fi
}

require_exact_publish_confirmation() {
  local key="$1" expected="$2" prompt="$3"
  ask "$key" "$prompt"
  if [[ "${!key}" != "$expected" ]]; then
    warn "confirmation did not match '$expected'; stopping before publish."
    exit 1
  fi
}

banner "Pre-CR VS Code Marketplace publish"

stage "Preflight" 3
say "This wizard publishes the VS Code extension only:"
step "$EXTENSION_ID@$EXTENSION_VERSION"
say "It uses the already agreed split: npm packages stay @pre-cr/core and @pre-cr/server; pre-cr-suite publishes to the VS Code Marketplace/VSIX path."
say "It does not store your Azure DevOps Personal Access Token in .env or in this repo."
require_cmd node
require_cmd pnpm
require_cmd corepack
require_cmd unzip
run_cmd node -e "const p=require('./packages/vscode-client/package.json'); console.log({name:p.name,publisher:p.publisher,version:p.version,main:p.main});"
run_cmd git status --short
confirm "Continue only if publisher is jakye, name is pre-cr-suite, version is 0.1.0, and the working tree status is expected?" || exit 1

stage "Verify publisher" 3
say "You said the Marketplace publisher now exists: $PUBLISHER_ID."
open_url "https://marketplace.visualstudio.com/manage/publishers/${PUBLISHER_ID}"
step "Confirm the publisher page opens for $PUBLISHER_ID."
step "Confirm your Microsoft account is a publisher owner or contributor."
step "Close this tab after confirming publisher access."
confirm "Did the $PUBLISHER_ID publisher page open and show that you have publish access?" || exit 1

stage "Create or confirm PAT" 5
say "VS Code Marketplace publishing uses Azure DevOps Marketplace auth."
say "For this first publish, use a PAT with Marketplace Manage scope."
open_url "https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token"
step "Follow the docs to create or confirm a Personal Access Token."
step "Use Organization: All accessible organizations."
step "Use Scopes: Custom defined -> Show all scopes -> Marketplace -> Manage."
step "Keep the PAT available for the next terminal prompt, then close the docs/Azure DevOps tabs when done."
pause "Press Enter after the PAT exists. Do not paste it into this wizard."

stage "Login vsce" 3
say "The next command prompts for the PAT in your terminal. The token is handled by vsce, not written by this script."
say "$ corepack pnpm --filter $EXTENSION_NAME exec vsce login $PUBLISHER_ID"
if confirm "Run vsce login for publisher $PUBLISHER_ID now?"; then
  run_cmd corepack pnpm --filter "$EXTENSION_NAME" exec vsce login "$PUBLISHER_ID"
else
  warn "vsce login is required before publish."
  exit 1
fi
run_cmd corepack pnpm --filter "$EXTENSION_NAME" exec vsce verify-pat "$PUBLISHER_ID"

stage "Final local gates" 5
say "Already done in this release-prep flow: VS Code build, typecheck, tests, and VSIX packaging."
say "Rerunning is safest if extension source changed after those checks."
if confirm "Rerun VS Code extension build, typecheck, test, and package now?"; then
  run_cmd corepack pnpm --filter "$EXTENSION_NAME" build
  run_cmd corepack pnpm --filter "$EXTENSION_NAME" typecheck
  run_cmd corepack pnpm --filter "$EXTENSION_NAME" test
  run_cmd corepack pnpm --filter "$EXTENSION_NAME" package
else
  say "Continuing with the completed VS Code Marketplace prep already recorded for this flow."
fi
verify_vsix_contents
confirm "Do the VSIX contents above look right for first Marketplace publish?" || exit 1

stage "Publish VSIX" 2
PUBLISHED_VERSION="$(marketplace_version_or_empty)"
if [[ "$PUBLISHED_VERSION" == "$EXTENSION_VERSION" ]]; then
  say "$EXTENSION_ID@$EXTENSION_VERSION is already visible on the Marketplace; skipping publish."
else
  say "This publishes the exact VSIX artifact: $VSIX_PATH"
  say "It avoids vsce version auto-increment so package.json is not changed and no version tag is created."
  require_exact_publish_confirmation PUBLISH_VSCODE_CONFIRM "publish ${EXTENSION_ID}@${EXTENSION_VERSION}" "Type exactly 'publish ${EXTENSION_ID}@${EXTENSION_VERSION}' to publish:"
  run_cmd corepack pnpm --filter "$EXTENSION_NAME" exec vsce publish --packagePath "$VSIX_FILE" --no-dependencies
fi

stage "Post-publish verification" 1
run_cmd corepack pnpm --filter "$EXTENSION_NAME" exec vsce show "$EXTENSION_ID"
open_url "https://marketplace.visualstudio.com/items?itemName=${EXTENSION_ID}"
step "Confirm the Marketplace listing loads for $EXTENSION_ID."
step "Close the Marketplace tab after verification."
say "If the listing is not visible immediately, wait a few minutes and rerun this final verification."

finish
